CREATE TABLE AUTORES(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    SENHA VARCHAR(255) NOT NULL,
    PRIMARY KEY(ID)
);
CREATE TABLE CURSOS(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL UNIQUE,
    CATEGORIA VARCHAR(100) NOT NULL,

    PRIMARY KEY(ID)
);

CREATE TABLE TOPICOS(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    TITULO VARCHAR(100) NOT NULL,
    MENSAGEM TEXT,
    DATA_CRIACAO DATETIME NOT NULL,
    STATUS VARCHAR(100) NOT NULL,
    AUTOR_ID BIGINT NOT NULL,
    CURSO_ID BIGINT NOT NULL,

    PRIMARY KEY(ID),
    CONSTRAINT FK_TOPICOS_AUTOR_ID FOREIGN KEY(AUTOR_ID) REFERENCES AUTORES(ID),
    CONSTRAINT FK_TOPICOS_CURSO_ID FOREIGN KEY(CURSO_ID) REFERENCES CURSOS(ID)
);
CREATE TABLE RESPOSTAS(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    MENSAGEM TEXT,
    TOPICO_ID BIGINT NOT NULL,
    DATA_CRIACAO DATETIME NOT NULL,
    AUTOR_ID BIGINT NOT NULL,
    SOLUCAO VARCHAR(100) NOT NULL,

    PRIMARY KEY(ID),
    CONSTRAINT FK_RESPOSTAS_AUTOR_ID FOREIGN KEY(AUTOR_ID) REFERENCES AUTORES(ID),
    CONSTRAINT FK_RESPOSTAS_TOPICO_ID FOREIGN KEY(TOPICO_ID) REFERENCES TOPICOS(ID)
);
CREATE TABLE USUARIOS(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    LOGIN VARCHAR(100) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,

    PRIMARY KEY(ID)
);